name: rok-api

services:
  app:
    build: .
    container_name: rok-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/rok_api_dev"
    networks:
      - infra

networks:
  infra:
    external: true
